function px_theta = pd_norm(x, mu, sigma)
    px_theta = ...
        bsxfun(@times, (2 * pi * sigma.^2).^(-0.5), ...
                        exp(bsxfun(@times, -0.5 ./ sigma.^2, ...
                                           bsxfun(@minus, x, mu).^2)));
