function p = pd_norm(x, mu, l)
    p = bsxfun(@times, (l / (2 * pi)).^(0.5), ...
                        exp(bsxfun(@times, -0.5 * l, ...
                                           bsxfun(@minus, x, mu).^2)));
