function opts = load_fret_defaults(function_name)
    opts = struct(...
        'has_labels', false, ...
        'remove_bleaching', false, ...
        'min_length', 0, ...
        'clip_range', [-0.2, 1.2], ...
        'max_outliers', inf, ...
        'strip_first', false, ...
        'blacklist', [], ...
        'show_progress', false);
