function u = u_defaults(K, D)
	if nargin < 2
		D = 1;
	end
    u = struct(...
    	'A', ones(K, K), ...
		'pi', ones(K, 1), ...
		'mu', 0.5 * ones(K, 1), ...
		'beta', 0.25 * ones(K, 1), ...
		'W', 50 * ones(K, D, D), ...
		'nu', 5 * ones(K, 1));
